algo_name: "aria_pga_init"

use_single_init_genotype: false

weight_fitness_obj: null

use_proba_fit: null

total_map_elites_evaluations: 500000

# PGA Parameters (for init only)
env_batch_size: 128

proportion_mutation_ga: 0.5
num_critic_training_steps: 1000
num_pg_training_steps: 100

replay_buffer_size: 1000000
critic_hidden_layer_size: [256, 256]
critic_learning_rate: 0.0003
greedy_learning_rate: 0.0003
policy_learning_rate: 0.001
noise_clip: 0.5
policy_noise: 0.2
discount: 0.99
reward_scaling: 1.0
transitions_batch_size: 256
soft_tau_update: 0.005
policy_delay: 2
