env_name: "ant_omni"

seed: ???
is_reset_based: true

# Robustness Optimisation parameters
aria:
  batch_size: 2048
  number_parallel_optimisations: 1
  number_robust_iterations_initial: 100
  number_robust_iterations_loop: 100
  perturbation_std: 0.02

  # Number reevals to estimate mean bd
  num_reevals_estimate_mean_initial: 2048

  learning_rate: 0.01

normaliser:
  min_fitness: -150.
  max_fitness: 100.
  min_distance: 0.
  max_distance: 30.

variation_fn:
  iso_sigma: 0.01
  line_sigma: 0.1

budget_per_eval: 4096
reeval:
  evals_per_gen: 32

grid_shape: [32, 32]
min_params: null
max_params: null
min_bd: -15.
max_bd: 15.
episode_length: 100
